// release-notes.js - the app's patch-note history, newest first.
// - The newest entry drives the one-time "What's new" popup shown on first launch
//   after an update (see renderer.js maybeShowPatchNotes / config.lastSeenVersion).
// - The full list backs the "Release notes" viewer in Settings > Help & About.
// Keep entries in Drew's voice, short, no em-dashes. Add the new version on top
// each cut; the popup and the history viewer both read from here automatically.
window.RELEASE_NOTES = [
  // Fork entry (German client + controller). Its version string is not the app version,
  // so it never triggers the "What's new" popup - it only shows in the Release notes viewer.
  {
    version: '3.0.7 · Fork (DE + Controller)',
    date: '2026-09-25',
    notes: [
      "German client:",
      "Rare Overseer Tablets (Aufseher-Tafel) price check works. The search sent the German base name to the English trade site, which answered 'Unknown item base type'.",
      "Unique items from a German client are found on trade again.",
      "German 'Außergewöhnlich' (exceptional) items are parsed, and the Dexterity requirement line is read.",
      "Controller (DualSense, USB):",
      "Every hotkey can also be put on a controller button. New: a close-only overlay button.",
      "Reprice with a controller: Square reads the price, exactly like right-clicking; you paste it yourself (Ctrl+V).",
      "Reprice:",
      "A price only counts once two frames in a row agree. A half-drawn dialog read 14 as 11.",
      "Faster: shorter waits between looks, no debug screenshot on every look.",
      "Net Worth:",
      "Setup wizard for controller players and custom UI sizes: calibrate, scan, align, check.",
      "Align tool on every scanned tab: drag boxes onto the numbers, row align (R), grid.",
      "OCR debug panel: see what the reader sees, tune filters per slot, learn digits from the image, copy/paste settings.",
      "High resolution reading for 4K/5K (setting). 5120x2880 is supported.",
      "A digit that lost to junk candidates is no longer dropped (262 read as 62).",
      "The list survives a restart. 'Often misread' tints are off by default (setting).",
    ],
  },
  {
    version: '3.0.7',
    date: '2026-09-18',
    notes: [
      "Forbidden Rites (0.5.5) support:",
      "Net Worth reads the Soul Cores tab again. GGG rearranged it and added 17 new cores. New ones won't have prices until the price feed lists them.",
      "If your league is set to Auto, you'll get a heads-up when it switches to a new league, with a button to pick yours.",
      "Items with the new soul cores socketed search the right socket count.",
      "Regex: new Expedition tablet mods added, Breach and Abyss tablet ranges updated.",
    ],
  },
  {
    version: '3.0.6',
    date: '2026-09-02',
    notes: [
      "Items with socket-bound league runes were searching the wrong socket count. Fixed for real this time.",
    ],
  },
  {
    version: '3.0.5',
    date: '2026-08-28',
    notes: [
      "Regex tab:",
      "Search on trade: one click turns your picked mods into a real trade site search and opens it in your browser",
      "Saved regexes now load back into the builder for editing. No more saved-and-locked-forever.",
      "Price Check:",
      "Price checking a stack of currency now shows the whole stack's value",
      "Items with a soul core socketed were searching the wrong socket count and finding nothing. Fixed.",
      "Linux:",
      "Wayland screen capture should actually work now. If you reported this, try again and tell me.",
    ],
  },
  {
    version: '3.0.4',
    date: '2026-08-16',
    notes: [
      "Cleaned up some unnecessary text throughout the app",
      "Improved clarity of troubleshooting for Reprice and Net Worth features",
    ],
  },
  {
    version: '3.0.3',
    date: '2026-08-15',
    notes: [
      "Desecration tab fixes:",
      "Tier dropdown selections weren't sticking, should be fixed now.",
      "Ticking/unticking outcomes no longer wipes the \"item with a hit\" price.",
      "Single-tier mods were labelled T2 when they were actually T1.",
    ],
  },
  {
    version: '3.0.2',
    date: '2026-08-15',
    notes: [
      "Reprice 2560x baked, should work at that resolution now.",
      "If reprice is breaking in a supported resolution, try manually calibrating first before submitting screenshots. User-adjusted settings like brightness/vibrance/gamma filters (NVIDIA overlays etc) mess with the auto-detection and are accountable for most misses.",
    ],
  },
  {
    version: '3.0.1',
    date: '2026-08-15',
    notes: [
      "Net Worth fixes",
      "Reprice now works in Windowed Fullscreen too, not just Windowed. Tested at 1920x1080, 1440x900, 1600x1200, 2560x1440.",
      "League Names now use GGG's direct translation library. If it reads in English that's becuase GGG themselves don't bother to translate some strings in some languages, randomly, if they feel like it, or not. It's on them now. It's ACTAULLY NOT MY FAULT.",
    ],
  },
  {
    version: '3.0.0',
    date: '2026-08-14',
    title: "The roadmap is clear and I have no new ideas for features. Other than bug fixes and adding support for new leagues, and pending any cool ideas from the community, this app is done. Thanks to everyone for submitting bug reports. Please keep reporting things as you find them. I'll keep this app running into the new leagues so enjoy!",
    notes: [
      "Desecrate now works on any rare item, not just ones that already have a desecrated mod.",
      "Bunch of UX and translation fixes.",
    ],
  },
  {
    version: '2.7.6',
    date: '2026-08-14',
    notes: [
      "Pinned search results now unpin when you leave the tab.",
      "Pinning no longer always flickers the detail card",
      "Price Check history now shows up on launch instead of after a tab switch.",
    ],
  },
  {
    version: '2.7.5',
    date: '2026-08-14',
    notes: [
      "Windows: the resize icon was covering the corner and blocking resize. Removed. That icon was only ever needed for Linux.",
      "Linux: the resize icon actually resizes now.",
    ],
  },
  {
    version: '2.7.4',
    date: '2026-08-14',
    notes: [
      "\"Open on trade site\" button was dead on arrival. Fixed. Thanks for the report.",
      "Search results now come back in your language",
      "Translated a bunch of stuff that was stuck in English (tabs, filters, Net Worth tab names)",
    ],
  },
  {
    version: '2.7.3',
    date: '2026-08-14',
    notes: [
      "fixed some settings issues",
      "Fixed more Multi-language issues",
    ],
  },
  {
    version: '2.7.2',
    date: '2026-08-14',
    notes: [
      "Fixed the \"Send Screenshots\" section of Reprice to suck less",
    ],
  },
  {
    version: '2.7.1',
    date: '2026-08-14',
    title: "New Reprice Feature, more user-submitted bug fixes.",
    notes: [
      "Reprice (new, experimental):",
      "New Reprice feature (Default F9) helps reprice your merchant tab items. Can be found in Settings -> Reprice",
      "Right click an item -> Rules applied -> new price pasted onto your clipboard -> ctrl + V.",
      "Rules can be customized / saved in the Settings tab.",
      "Tested at 1080p, 1440x900, 1600x1200, 2560x1440.",
      "Submit the 3 required screenshots to get an unsupported resolution added",
      "Price Check:",
      "\"Open on trade site\" button.",
      "Some currencies failed to price check (Kamasa's / Yaomac's / Vaal orbs of sacrifice). Fixed.",
      "Net Worth:",
      "The EXPERIMENTAL banner is now dismissible. Screenshot submission lives permanently in Settings > Net Worth.",
      "Misc:",
      "Screen capture (SHOULD) follow the game across monitors.",
      "Settings sections start at the same height.",
      "Linux: capture and Ctrl+F focus fixes (hopefully)",
    ],
  },
  {
    version: '2.7.0',
    date: '2026-08-11',
    title: "New Theme, Random Fixes",
    notes: [
      "New Theme - Industry. Enjoy.",
      "Currency:",
      "Arb values under 3% were unreadable (1.81:1 → 4.78:1)",
      "Fixed an issue where clicking into a Fix Rate input would unpin the tooltip",
      "Price Check:",
      "Parser was English-only since 2.6.0. Non-English users parsed items against the wrong dictionary. My bad.",
      "Currency search results back button changed to match Equipment search results back button.",
      "Regex:",
      "Ctrl+V should now work for everyone, including non-english users (hopefully)",
      "Net Worth:",
      "You can now spam F7 as fast as the app pops back up. No need to wait for processing each tab any more. Should feel much faster to go through all your currency tabs.",
      "Drag-to-bottom behavior now matches Currency tab.",
      "Added a 3-entry legend at the top. Amber and Red legend values only appear when one of your scanned tabs contains one.",
      "Row highlights now highlight the entire row",
      "The Submit Screenshot screenshot preview window now closes when it loses focus.",
      "The Submit Screenshot button's disabled vs enabled status is no longer identical",
      "Settings:",
      "Organized things a bit better, cleaned up some verbiage",
      "Splash:",
      "F6 hint + \"Windowed or Windowed Fullscreen\" requirement shown every launch",
      "App-wide:",
      "Fixed a bug where screen capture could cause the app to appear visible but be inactive, requiring f6 twice to restore",
      "Industry Theme added",
      "Fixed a few missed translations that stayed static in English when the language was swapped",
    ],
  },
  {
    version: '2.6.13',
    date: '2026-08-10',
    title: "Bug report improvements",
    notes: [
      "Bug reports now opt-out collect limited machine info to assist in debugging because I'm having trouble fixing some user reported errors in the Regex tab.",
      "The last item Ctrl+V'd into the app is included in the bug report.",
      "Fixed a bug where Ctrl+V into the Regex tab did nothing if you'd clicked the pattern box first.",
      "Privacy policy updated to reflect the changes",
    ],
  },
  {
    version: '2.6.12',
    date: '2026-08-10',
    notes: [
      "Ctrl+V a tablet or waystone into the Regex tab should now work for non-english clients",
    ],
  },
  {
    version: '2.6.11',
    date: '2026-08-10',
    notes: [
      "Auto-Calibration broke for some views, causing strange offsets that ruined glyph matching for those users. I've restored the ability to calibrate yourself. If you notice glyph matching is bad, try manual calibration. If that doesn't help, send me stash screenshots.",
    ],
  },
  {
    version: '2.6.10',
    date: '2026-08-09',
    title: "More negative value fixes",
    notes: [
      "Last \"fix\" caused a mirror issue with some items. This should hopefully be the last fix needed, pending any edge cases I couldn't find.",
    ],
  },
  {
    version: '2.6.9',
    date: '2026-08-09',
    title: "More Random Fixes from user feedback",
    notes: [
      "\"When price checking waystones, the \"waystone drop chance\" property is always hidden. Please include it by default as this has a big sway on value.\"",
      "  Fixed now.",
      "\"Please make the pop out comparison panel open on the right side if the panel is offscreen/overlay is all the way to the left edge of the screen.\"",
      "  Good feedback. Done.",
      "The third guy wrote an essay but basically negative search values were not properly inverted. This SHOULD be fixed now but please report any searches that should auto-search with negative values but instead search positive.",
    ],
  },
  {
    version: '2.6.8',
    date: '2026-08-09',
    notes: [
      "Minor tweaks to the Net Worth tab, and small updates to the amber lines.",
    ],
  },
  {
    version: '2.6.7',
    date: '2026-08-09',
    notes: [
      "General:",
      "Wombgifts should now price accurately.",
      "iLevels for all items should now display in results row, and as a tooltip compare line. iLevel was just being hidden for no reason for basically all items. If you guys notice items that should display iLevels and don't, submit a bug report.",
      "Net Worth:",
      "Sending screenshots was broken for the same reason your tabs weren't calcing properly. It now asks you to visually confirm if we got the stash tab and if not, it fallbacks to whole gamecsreen capture.",
      "Confirm screen won't submit until you verify every screenshot contains a stash tab",
      "Capturing shows a spinner now instead of looking frozen.",
      "Amber rows in Net Worth should now be visible. They denote rows with known issues.",
      "Currency tab is the #1 to send, but other annoying ones include Soul Cores, Breach, Ancient Augments, Idols and Kalguuran Runes",
      "Price Check:",
      "Quality 20 and Greater Iron Rune toggles are always in Miscellaneous now.",
      "Some mod sliders weren't giving full ranges, should be fixed",
      "Desecrated mods were folding into Explicits, which is technically correct for finding best matches. But visually it hides what mod is desecrated. Now the explicit with the folded desecrated line has a green tinge so you know without having to unfold the mods to see it.",
    ],
  },
  {
    version: '2.6.6',
    date: '2026-08-07',
    notes: [
      "Ctrl+F prices almost all currency now.",
    ],
  },
  {
    version: '2.6.5',
    date: '2026-08-07',
    notes: [
      "\"Manual typed search on a currency type item doesn’t show any price. it doesn’t bring you to the same screen as ctrl+f on the currency\" - Fixed",
    ],
  },
  {
    version: '2.6.4',
    date: '2026-08-07',
    title: "Corrections",
    notes: [
      "I corrected my previous patch notes",
      "The \"calibration\" button was a lie. Its automatic so it shouldn’t exist unless auto calibration fails. So that’s how it works now. Probably...",
    ],
  },
  {
    version: '2.6.3',
    date: '2026-08-07',
    title: "Net Worth calibrates itself",
    notes: [
      "Net Worth:",
      "Calibration is automatic. Let me know if it doesn’t work.",
      "User-submitted stash tab screenshots have improved the reader. I still need more data especially at ultra-wide, and ultra-ultra-ultra-ultra-ultra wide some of you wackos run at.",
      "If net-worth calc doesn’t work well for you still, submit using the in-tab button. Next patch, it should work for you.",
      "Amber rows in Net Worth means known to have errors. Double check them.",
      "Price Check:",
      "Fixed a bug with negative mods. Thanks to the user who submitted the Atziri Step report.",
      "General:",
      "Linux users should now be able to drag-to-resize. Hopefully. Let me know.",
    ],
  },
  {
    version: '2.6.2',
    date: '2026-08-05',
    title: "User feedback changes and bug fixes",
    notes: [
      "User feedback changes:",
      "A \"Search by Name\" feature. You can access it by clicking on the name of the item in your search window, or by clicking \"Search by name\" in the search history screen. Good for anything you can't Ctrl+C, like runestones in the combine dialogue or Ritual reward choices.",
      "A \"Listed\" filter in the Misc section that lets you ignore listings older than whatever threshold you pick, removing them from the listings so they can't affect the suggested price.",
      "Arbitrage routes now estimate the gold cost, so you can put in the quantity you're starting with and see the whole bill before you commit to the first trade instead of finding out halfway through.",
      "Routes are quoted in whole units now, since Ange won't let you spend a fraction of an item and \"1.3 divine\" was never something you could actually trade.",
      "Unidentified uniques now price properly. If the base only has one unique it just knows what you're holding, and if it has several, like a Sapphire that could be a Grand Spectrum or a Voices, it shows you the candidates and you pick the one you have. There is also an Identified filter in the Misc section now, and unidentified listings are marked in the results.",
      "Bug report fixes:",
      "A few versions ago I regressed the comparison window when adding language support. My bad. Thanks to the user who submitted the feedback.",
      "Uniques were searching poorly. They now search on the rolls that actually vary between copies, so you get compared against uniques rolled like yours rather than the cheapest one on the market.",
      "Unique mods, along with Time-Lost and Sanctum mods, were hidden in the add-a-mod screen. Over 1,400 mods in total, all searchable now.",
      "Buttons and labels looked identical. If it has an outline you can click it, if it doesn't you can't.",
    ],
  },
  {
    version: '2.6.1',
    date: '2026-08-04',
    title: "Net Worth needs community help to work properly",
    notes: [
      "Net Worth is now marked EXPERIMENTAL. Added a new button to submit your stash tabs to help me build support. If it doesn't work for you, please follow the in-app process to send me your screenshots.",
      "Fixed: opening Miscellaneous on a price check blanked the screen until you restarted the app.",
      "Fixed: Ctrl+F did nothing if your game is not in English. The item was copied fine, the app just refused to read it.",
      "Fixed: gems priced as if they had no level on non-English clients, and rune sockets did not show.",
    ],
  },
  {
    version: '2.6.0',
    date: '2026-07-29',
    title: 'Русский · Português · Deutsch · Français · Español',
    notes: [
      'The app now runs in Russian, Brazilian Portuguese, German, French or Spanish, and price checks items copied from those clients.',
      'Settings → App → Language. One setting covers the app and the item reader.',
      'Currency and item names come from the game\'s own text, so they match what your stash says.',
    ],
  },
  {
    version: '2.5.8',
    date: '2026-07-28',
    title: 'Linux: screen capture',
    notes: [
      'Linux only. Nothing changes on Windows - every fix in this build sits behind a platform check.',
      'Fixed: Calibrate just made the overlay flicker and did nothing. Screen capture on Linux goes through your desktop\'s share dialog, which browsers only allow off a real click - and ours was triggered by a hotkey and a button that hands off to the background, so it was refused instantly.',
      'The share dialog now also opens while the overlay is still on screen, instead of behind a hidden window.',
    ],
  },
  {
    version: '2.5.7',
    date: '2026-07-28',
    title: 'Linux: price check actually works',
    notes: [
      'Linux only. Nothing changes on Windows - every fix in this build sits behind a platform check.',
      'Price check works. Every Linux build before this one shipped without the item parser: our packaging step for Linux skipped building it, so the whole Price Check and Desecrate side of the app failed on any item. Nothing to do with the game, the clipboard or the desktop - our build.',
      'The hotkey pressing Ctrl+C in the game for you is now a setting, off by default. On GNOME Wayland it makes the desktop ask "Allow Remote Interaction" every single press. Leave it off and copy the item yourself, or set "linuxCopyViaXdotool" to true in the config file if you want one press and don\'t mind the prompt.',
    ],
  },
  {
    version: '2.5.6',
    date: '2026-07-28',
    title: 'Linux: price check in one press',
    notes: [
      'Linux only. Nothing changes on Windows - every fix in this build sits behind a platform check.',
      'Price check works on one press again if you have xdotool installed. The app drives the game\'s copy through xdotool, which does reach it, unlike the input library the app uses everywhere else. Without xdotool it still falls back to whatever you copied yourself.',
      'Fixed: hiding the overlay took three seconds. That was the new window-focus code shelling out and blocking everything while it waited.',
      'Stash capture asks to share your screen once per launch, and reads frames from that. Screen capture on a Wayland desktop has to go through the system\'s own share dialog - the shortcut around it returned a black picture, which is why calibration showed a black screen.',
    ],
  },
  {
    version: '2.5.5',
    date: '2026-07-28',
    title: 'Linux batch',
    notes: [
      'Linux only. Nothing changes on Windows - every fix in this build sits behind a platform check.',
      'Esc hides the overlay without having to click it first. It was a keypress handled inside the window, and the window never holds keyboard focus there.',
      'If you have xdotool installed, the app can now see which window is active and raise the game itself. Command hotkeys use it, so /hideout stops firing into whatever window you happen to be in. Without xdotool nothing changes.',
      'Stash capture (F7) gets a shot: the launcher now presents an X11 session to the app, which should put screen capture on the X11 path instead of the portal that can\'t show its dialog behind a fullscreen game. Untested - tell me if it comes back black.',
      'Non-English client? Set "gameWindowMatch" in the config file to your window title.',
    ],
  },
  {
    version: '2.5.4',
    date: '2026-07-28',
    title: 'Linux fixes, take two',
    notes: [
      'Linux only. Nothing changes on Windows - every fix in this build sits behind a platform check.',
      'The X11 backend flag is now baked into the packaged launcher itself, so you no longer need to pass --ozone-platform=x11 by hand. 2.5.3 claimed this and was wrong: the flag has to be on the real command line, and neither of the two ways the app tried to do that reached it.',
      'The price-check hotkey falls back to your clipboard. If the app can\'t drive the game\'s copy (it can\'t on a GNOME Wayland session), press Ctrl+C in game yourself and then the hotkey, and it prices what you copied.',
      'Command hotkeys like /hideout fire again. They were checking "is the game focused", which has no answer outside Windows, and treating no-answer as no.',
    ],
  },
  {
    version: '2.5.3',
    date: '2026-07-28',
    title: 'Linux fixes',
    notes: [
      'Linux only. Nothing changes on Windows - every fix in this build sits behind a platform check.',
      'Tried to force the X11 backend flag at launch, since without it the GPU process crashes and no hotkey can register. This attempt did NOT work - keep passing --ozone-platform=x11 yourself on 2.5.3.',
      'The hide button actually hides the overlay. It was only turning it transparent, which does nothing without a compositor honouring it.',
      'The overlay no longer shows up at launch before you press the toggle.',
      'Stash capture (F7) fails with an error after 8 seconds instead of sitting on "Scanning" forever. Capture on GNOME still needs the desktop portal - separate work.',
      'Update errors are logged instead of blocking the app behind an error dialog.',
    ],
  },
  {
    version: '2.5.2',
    date: '2026-07-28',
    title: 'Your feedback, shipped',
    notes: [
      'Skill gems price check properly now. Gem level and quality drive the search, and a gem copied while socketed discounts your gear\'s +levels, so a level 20 gem searches as 20 instead of 32.',
      'Suggested floor shows the other currencies too. 0.7 div now also reads in exalted and chaos, so you don\'t need the exchange rate memorized.',
      'Currency buckets collapse with the chevron in their header, and you can drag whole cards into the order you want. A collapsed bucket still shows its cheapest payment.',
      'Fixed: clicking Search, or another filter box, straight out of a filter field took two clicks.',
      'Fixed: long prices overlapped the item name in the results list.',
    ],
  },
  {
    version: '2.5.1',
    date: '2026-07-27',
    title: 'Tutorial covers the new tabs',
    notes: [
      'The tutorial now spotlights Net Worth, Regex and Grand Expedition, offered right after the Price Check + Desecrate run',
      'Each of them has its own Replay chip in Settings → Help & About, so you can revisit one tab instead of the whole tour',
      'Regex and Grand Expedition spotlight a demo build and a demo roster, so you see a real pattern and a real verdict instead of empty boxes. Your own picks come back when the tour ends',
      'Command Hotkeys got a mention in the tutorial\'s Settings step',
    ],
  },
  {
    version: '2.5.0',
    date: '2026-07-27',
    title: 'Regex, Grand Expedition, Command Hotkeys + tab management',
    notes: [
      'Regex tab - waystone/tablet builder (real roll ranges, thresholds, exclusions), tablet subtype filter, seed-from-copied-item, saved regex buckets with 1-click copy, custom hand-written regexes',
      'Command Hotkeys (Settings → Hotkeys) - safe chat commands on a keypress, 17-command list + custom /command with args, only fires with the game focused',
      'Grand Expedition tab - rumor picker (type-to-pick + click), Aldur SPEND/SAVE verdict with normalized community scores (3-expedition minimum), logbook summary, copy-paste map-note tag that rebuilds the roster, prep guide with in-game tablet/waystone windows + trade links, rune chain tracker, run history',
      'Tab management - drag-to-reorder, ✕ to hide (Desecrate/Net Worth/Regex/Grand Expedition; Currency + Price Check permanent), visibility toggles in Settings incl. new Net Worth toggle',
      'Small stuff: Net Worth TOTAL icons sized up with icon mode; wording fixes ("currency tabs")',
    ],
  },
  {
    version: '2.4.1',
    date: '2026-07-27',
    title: 'Hotfix - 2.4.0 launch crash',
    notes: [
      "Fixed a packaging bug that left a data file out of the 2.4.0 build, so it failed to launch with a 'Cannot find module' error. Sorry about that - if you grabbed 2.4.0, this update gets you running.",
    ],
  },
  {
    version: '2.4.0',
    date: '2026-07-27',
    title: 'Stash Tab Auto-Calculator (Net Worth Tab)',
    notes: [
      "Net Worth tab - 1920 x or larger recommended. Use the Calibration button in Net Worth settings. Select any currency window frame, calibrate the window (auto snap works well) and you're done.",
      "F7 by default caps the current open tab in-game and adds it to the Net Worth tab.",
      "Supports: Currency Tab, Abyss, Ritual, Essence, All 5 Rune Subtabs, Delirium, Breach, and Expedition.",
      "Shows your total net worth in Div, with a Mirror conversion for richies.",
      'Can toggle "Duplicates allowed" in settings - allows people to register multiple duplicate tabs, for those of you who separate things into multiple instances of the same tabs.',
      "Toggle on or off any tab, and any row within the tab",
      "Edit the value if the parser got it worng.",
      "It's not perfect but it works pretty well. Some icons in particular are brutal and obfuscate the number. I'm done wasting time grinding parser values. It's relatively high accuracy and you can enable the toggle to show you the rating. Anything above 80% is usually good but it can sometimes make mistakes. You can edit in-line any value it gets wrong.",
      "I also updated support for various currency items like Raven's Reflection in pricing and currency tab(s).",
      "Enjoy!",
    ],
  },
  {
    version: '2.3.5',
    date: '2026-07-26',
    title: 'OpenDyslexic support, Linux (EXPERIMENTAL), Patch Notes Modal changes',
    notes: [
      "Added OpenDyslexic, a dyslexia-friendly font. Toggle it on in Settings under the App section. Applies to the whole app.",
      "Experimental Linux support (AppImage). It forces XWayland automatically, so the overlay, hotkey and item-copy work without you adding any command line flags. It's experimental - report anything that misbehaves.",
      "The patch-notes popup now scrolls through the full history, with a version sidebar on the left. Click any version to jump to it.",
    ],
  },
  {
    version: '2.3.4',
    date: '2026-07-25',
    title: 'API Rates & Small QoL Fixes',
    notes: [
      "Fixed API problems, which in some cases was causing artificial (local only) timeouts. Removed entirely. Any timeout you get is now real. Don't spam!",
      "Listings now paginate at 10 and you can load more. This further improves API usage rates.",
      "Currency API rate handling - 2 new settings inside the Currency settings let you control the rate the app pings GGG for currency pairs. At HIGH it refreshes all primary pairs every 2.5m, and scales down from there. Slider 1 is how it polls while you're viewing the Currency tab; Slider 2 is how it polls while the app is backgrounded or the tab isn't selected. These calls use the same bucket as your item searches, so if you hit rate limits often while ctrl+F'ing gear, tune down Slider 2.",
      "Exceptional bases were searching with runes turned on, which threw off the results. Cleaned that up so they search like the game does (quality 20, no runes, uncorrupted). Should match what you'd expect now.",
      "Added patch notes that pop up after an update so you can see what I'm up to.",
      "Added a way to re-read the patch notes any time from the App Settings.",
      "Fixed small dyslexic toggle bug, now (should) accurately swap all instances of currency names on the price check tab.",
      "Drag-to-reorder on Currency Tab, as well as drag out of bucket and drop to delete.",
      "Add more than one currency to a bucket at a time.",
      "Added support for some missed Verisium stuff.",
      "Pagination applied to Desecration tab + PC tab.",
      "App now remembers what tab you closed it on and opens to that tab.",
      "Tutorial updated.",
    ],
  },
];
